os: osx
osx_image: xcode9

language: java

before_script:
  - export P12="CodeSigningCert.p12"
  - export KEYCHAIN="build.keychain"
  - echo $CODE_SIGN_CERT | base64 --decode > $P12
  - security create-keychain -p mysecretpassword $KEYCHAIN
  - security default-keychain -s $KEYCHAIN
  - security unlock-keychain -p mysecretpassword $KEYCHAIN
  - security set-keychain-settings $KEYCHAIN
  - security import $P12 -k $KEYCHAIN -P $CODE_SIGN_PWD -T /usr/bin/codesign
  - |-
    security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k mysecretpassword $KEYCHAIN

script:
  - cd kse
  - ./gradlew dmg

deploy:
  provider: releases
  api_key:
    secure: "CfG60H4ut77byX9Nn6A9khS9XzQ/pW3warAbp+GROEZ7lBGgvbKzUvfaUvYaU42Gj9u66AtAriWLWR+gQsOBO4Bf9d8Nm2kCbUObXAEeaqZiuxS0O6ygSXh5zOwf4rGJGvQNuz8TyGqcXCoCrqNxXLn9LN0rqM8We3Fr3oGo2o5G78YdwH205eSGKoZqAHwRCpbaHQtF+uOxidZbUpSX7eGRR1j4lE/UP9ILYwxX61yNnGHT3ruE+bkEZ/da4RH5KHSjJKxca8E3BlgjwMOmIqMkKrzdXBqlKIKRn2HyPTy/l8Lk3g68rD7vRJgwKaKnJ+o7w/wYSqzjgwK7f6XUp+BD8Ci2r/2swHP+LMa+0Uq+Uvk4vs0fB+AadRgM0B8JRn5Tnfc2tGISgYTqjGEBKu/5cufuxEvlIRGx/nd8QMKatMfWbiLqDF0paobNQ+tJ5xK/ixx826bZavKuOuRSIuykwmRtsuoVcxqogoJ/vJgyROGel+iwAEjMmbo4sLSXjC80IflteIZkT255VMEvlqLFmdP75/vzwWDepueFkXg9CP8O5AWAPDeSTFm/lMxmTRaV6yyCUNZCZuTlsFKTpEdLCDBnt58rRUbT6itSN5XEB6ssEU9HADOfHyFGLixJhtkCv/XTz9Ft0uOlmsn7x9aSy65XtI40LnkvgjBPiOU="
  file_glob: true
  file: ${TRAVIS_BUILD_DIR}/kse/build/distributions/kse-*.dmg
  skip_cleanup: true
  draft: true
  on:
    tags: true