language: java

jdk:
  - oraclejdk8
 
# NSIS version in Travis CI's Ubuntu Trusty image is 2.46 from 2009, which is way too old  
#addons:
#  apt:
#    packages:
#    - nsis

script:
  - cd kse
  - ./gradlew build
